### ISSUE TITLE
Proposal for creating a generic convert function

### ISSUE THREAD

**Issue by alexiusacademia** [alexiusacademia/unitconvert#10]
The proposal if to create a generic function for all conversions. So that we don't have to write the function content

```go
if from.Type != DischargeUnit || to.Type != DischargeUnit {
    return 0, invalidInputTypes
}

if from == to {
	return v, nil
}

factor, ok := conversionFactors[from][to]
if !ok {
	return 0, unsupportedDestinationError
}

return v * factor, nil
```

since all of the conversion functions matches the signature of this content. 

Any comments and suggestions are welcome.

**Comment by engrleir** [comment]
Maybe create a convert function that just checks if the types are not equal
``` go
// Check if the types are equal
if from.Type != to.Type {
    return 0, invalidInputTypes // improve the error showing a message about the from and to types
}

if from == to {
	return v, nil
}

factor, ok := conversionFactors[from][to]
if !ok {
	return 0, unsupportedDestinationError
}

return v * factor, nil
```

**Comment by alexiusacademia** [comment]
Yes that is the possible solution since the original function is becoming redundant when a new conversion for a certain `UnitType` is written. 

This is an api breaking change but we still not on a production version (e.g. v1.0.0), hence we can just put this on a patch version maybe? 

The rule is to not mix `UnitType`s in conversion and this still follows that.
